apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employee
    run: employee
  name: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
   metadata:
    labels:
      app: employee
   spec:
     containers:
       - image: 10.128.0.17:5000/syedhajirali/employee:${BUILD_NUMBER}   
         name: employee     

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
    run: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
   metadata:
    labels:
      app: backend
   spec:
    containers:
    - image: 10.128.0.17:5000/syedhajirali/mysql:${BUILD_NUMBER}
      imagePullPolicy: IfNotPresent
      name: backend
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee
  name: employee
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: employee
  sessionAffinity: None
  type: NodePort
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: backend
  sessionAffinity: None
  type: ClusterIP
