apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employee
    run: employee
  name: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
   metadata:
    labels:
      app: employee
   spec:
    containers:
    - image: 10.128.0.12:5000/syedhajirali/employee:${BUILD_NUMBER}
      imagePullPolicy: IfNotPresent
      name: employee
    imagePullSecrets:
     - name: dockersec


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee
  name: employee
  namespace: default
spec:
  ports:
  - nodePort: 30600
    port: 9010
    protocol: TCP
    targetPort: 9010
  selector:
    app: employee
  sessionAffinity: None
  type: NodePort
