apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employee1
    run: employee1
  name: employee1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee1
  template:
   metadata:
    labels:
      app: employee1
   spec:
     containers:
       - image: 10.128.0.12:5000/syedhajirali/employee:${BUILD_NUMBER}
         imagePullPolicy: IfNotPresent
         name: employee1


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee1
  name: employee1
  namespace: default
spec:
  ports:
  - nodePort: 30455
    port: 9010
    protocol: TCP
    targetPort: 9010
  selector:
    app: employee1
  sessionAffinity: None
  type: NodePort
